name: geomar-challenge-env
channels:
  - conda-forge
dependencies:
  - nomkl
  # core scipy packages
  - numpy
  - scipy
  - matplotlib-base
  - pandas
  - xarray
  - dask
  - distributed
  - dask-jobqueue
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  # pyviz
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - seaborn
  # geospatial
  - iris
  - cartopy
  - cartopy_offlinedata
  - basemap
  - netcdf4
  - h5py
  - h5netcdf
  # geoscience-related
  - gsw
  - windspharm
  # intake-related
  - intake
  - intake-xarray
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  # jupyter-related
  - ipykernel
  # xarray-related
  - xhistogram
  - pip
  - pip:
    - fastparquet